// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QUANLYBANMAYANH_NHOM24.Models;

#nullable disable

namespace QUANLYBANMAYANH_NHOM24.Migrations
{
    [DbContext(typeof(QuanLyBanMayAnhContext))]
    [Migration("20241207203750_AddAnhdanhmucToDanhMuc")]
    partial class AddAnhdanhmucToDanhMuc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QUANLYBANMAYANH_NHOM24.Models.ChiTietDonHang", b =>
                {
                    b.Property<int>("Idchitietdonhang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idchitietdonhang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idchitietdonhang"));

                    b.Property<int>("Iddonhang")
                        .HasColumnType("int")
                        .HasColumnName("iddonhang");

                    b.Property<int>("Idsanpham")
                        .HasColumnType("int")
                        .HasColumnName("idsanpham");

                    b.Property<int>("Soluong")
                        .HasColumnType("int")
                        .HasColumnName("soluong");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Idchitietdonhang")
                        .HasName("PK__ChiTietD__D719A734F7B70079");

                    b.HasIndex("Iddonhang");

                    b.HasIndex("Idsanpham");

                    b.ToTable("ChiTietDonHang", (string)null);
                });

            modelBuilder.Entity("QUANLYBANMAYANH_NHOM24.Models.DanhMuc", b =>
                {
                    b.Property<int>("Iddanhmuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iddanhmuc");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Iddanhmuc"));

                    b.Property<string>("Anhdanhmuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Anhdanhmuc");

                    b.Property<string>("Tendanhmuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tendanhmuc");

                    b.HasKey("Iddanhmuc")
                        .HasName("PK__DanhMuc__F4CD32E37138F45C");

                    b.ToTable("DanhMuc", (string)null);
                });

            modelBuilder.Entity("QUANLYBANMAYANH_NHOM24.Models.DanhMucCon", b =>
                {
                    b.Property<int>("Iddanhmuccon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iddanhmuccon");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Iddanhmuccon"));

                    b.Property<int>("Iddanhmuc")
                        .HasColumnType("int")
                        .HasColumnName("iddanhmuc");

                    b.Property<string>("Tendanhmuccon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tendanhmuccon");

                    b.HasKey("Iddanhmuccon")
                        .HasName("PK__DanhMucC__CE970A9A06C7B2DB");

                    b.HasIndex("Iddanhmuc");

                    b.ToTable("DanhMucCon", (string)null);
                });

            modelBuilder.Entity("QUANLYBANMAYANH_NHOM24.Models.DiaChiGiaoHang", b =>
                {
                    b.Property<int>("Iddiachi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iddiachi");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Iddiachi"));

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("diachi");

                    b.Property<int>("Idnguoidung")
                        .HasColumnType("int")
                        .HasColumnName("idnguoidung");

                    b.Property<string>("Sdtnguoinhan")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("SDTnguoinhan");

                    b.Property<string>("Tennguoinhan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tennguoinhan");

                    b.HasKey("Iddiachi")
                        .HasName("PK__DiaChiGi__A8D1197358181C2E");

                    b.HasIndex("Idnguoidung");

                    b.ToTable("DiaChiGiaoHang", (string)null);
                });

            modelBuilder.Entity("QUANLYBANMAYANH_NHOM24.Models.DonHang", b =>
                {
                    b.Property<int>("Iddonhang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iddonhang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Iddonhang"));

                    b.Property<int>("IdPttt")
                        .HasColumnType("int")
                        .HasColumnName("idPTTT");

                    b.Property<int>("Iddiachi")
                        .HasColumnType("int")
                        .HasColumnName("iddiachi");

                    b.Property<int>("Idnguoidung")
                        .HasColumnType("int")
                        .HasColumnName("idnguoidung");

                    b.Property<DateTime?>("Ngaydat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngaydat")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Trangthai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Đang xử lý")
                        .HasColumnName("trangthai");

                    b.HasKey("Iddonhang")
                        .HasName("PK__DonHang__6DCE9B0043CEA171");

                    b.HasIndex("IdPttt");

                    b.HasIndex("Iddiachi");

                    b.HasIndex("Idnguoidung");

                    b.ToTable("DonHang", (string)null);
                });

            modelBuilder.Entity("QUANLYBANMAYANH_NHOM24.Models.DonHangKhuyenMai", b =>
                {
                    b.Property<int>("IddonhangKm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iddonhangKM");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IddonhangKm"));

                    b.Property<int>("Iddonhang")
                        .HasColumnType("int")
                        .HasColumnName("iddonhang");

                    b.Property<int>("Idkhuyenmai")
                        .HasColumnType("int")
                        .HasColumnName("idkhuyenmai");

                    b.HasKey("IddonhangKm")
                        .HasName("PK__DonHangK__B719AEBCBE29CEE4");

                    b.HasIndex("Iddonhang");

                    b.HasIndex("Idkhuyenmai");

                    b.ToTable("DonHangKhuyenMai", (string)null);
                });

            modelBuilder.Entity("QUANLYBANMAYANH_NHOM24.Models.GioHang", b =>
                {
                    b.Property<int>("IdGioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idGioHang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGioHang"));

                    b.Property<int>("Idnguoidung")
                        .HasColumnType("int")
                        .HasColumnName("idnguoidung");

                    b.Property<int>("Idsanpham")
                        .HasColumnType("int")
                        .HasColumnName("idsanpham");

                    b.Property<int>("Soluong")
                        .HasColumnType("int")
                        .HasColumnName("soluong");

                    b.HasKey("IdGioHang")
                        .HasName("PK__GioHang__3FD868429D998115");

                    b.HasIndex("Idnguoidung");

                    b.HasIndex("Idsanpham");

                    b.ToTable("GioHang", (string)null);
                });

            modelBuilder.Entity("QUANLYBANMAYANH_NHOM24.Models.Hang", b =>
                {
                    b.Property<int>("Idhang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idhang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idhang"));

                    b.Property<string>("Tenhang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tenhang");

                    b.HasKey("Idhang")
                        .HasName("PK__Hang__ABCF290EBA8DEC53");

                    b.ToTable("Hang", (string)null);
                });

            modelBuilder.Entity("QUANLYBANMAYANH_NHOM24.Models.KhuyenMai", b =>
                {
                    b.Property<int>("Idkhuyenmai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idkhuyenmai");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idkhuyenmai"));

                    b.Property<int>("Giamgiaphantram")
                        .HasColumnType("int")
                        .HasColumnName("giamgiaphantram");

                    b.Property<string>("Makhuyenmai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("makhuyenmai");

                    b.Property<DateOnly>("Ngaybatdau")
                        .HasColumnType("date")
                        .HasColumnName("ngaybatdau");

                    b.Property<DateOnly>("Ngayhethan")
                        .HasColumnType("date")
                        .HasColumnName("ngayhethan");

                    b.HasKey("Idkhuyenmai")
                        .HasName("PK__KhuyenMa__59172652E4D44434");

                    b.HasIndex(new[] { "Makhuyenmai" }, "UQ__KhuyenMa__77F420CC6335069A")
                        .IsUnique();

                    b.ToTable("KhuyenMai", (string)null);
                });

            modelBuilder.Entity("QUANLYBANMAYANH_NHOM24.Models.NguoiDung", b =>
                {
                    b.Property<int>("Idnguoidung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idnguoidung");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idnguoidung"));

                    b.Property<string>("AnhNguoiDung")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("anh_nguoi_dung");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Gioitinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("gioitinh");

                    b.Property<string>("Matkhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("matkhau");

                    b.Property<DateOnly?>("Ngaysinh")
                        .HasColumnType("date")
                        .HasColumnName("ngaysinh");

                    b.Property<string>("Sdt")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("SDT");

                    b.Property<string>("TenNguoiDung")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ten_nguoi_dung");

                    b.HasKey("Idnguoidung")
                        .HasName("PK__NguoiDun__7C5001957141FBC3");

                    b.HasIndex(new[] { "Email" }, "UQ__NguoiDun__AB6E6164ACB2545F")
                        .IsUnique();

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("QUANLYBANMAYANH_NHOM24.Models.NguoiDungPhanQuyen", b =>
                {
                    b.Property<int>("IdNdpq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idNDPQ");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNdpq"));

                    b.Property<int>("Idnguoidung")
                        .HasColumnType("int")
                        .HasColumnName("idnguoidung");

                    b.Property<int>("Idphanquyen")
                        .HasColumnType("int")
                        .HasColumnName("idphanquyen");

                    b.HasKey("IdNdpq")
                        .HasName("PK__NguoiDun__C23E414D02ED019F");

                    b.HasIndex("Idnguoidung");

                    b.HasIndex("Idphanquyen");

                    b.ToTable("NguoiDungPhanQuyen", (string)null);
                });

            modelBuilder.Entity("QUANLYBANMAYANH_NHOM24.Models.PhanQuyen", b =>
                {
                    b.Property<int>("Idphanquyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idphanquyen");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idphanquyen"));

                    b.Property<string>("TenPq")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tenPQ");

                    b.HasKey("Idphanquyen")
                        .HasName("PK__PhanQuye__23C0CE5F990D7A0B");

                    b.HasIndex(new[] { "TenPq" }, "UQ__PhanQuye__FB74F8710F305027")
                        .IsUnique();

                    b.ToTable("PhanQuyen", (string)null);
                });

            modelBuilder.Entity("QUANLYBANMAYANH_NHOM24.Models.PhuongThucThanhToan", b =>
                {
                    b.Property<int>("IdPttt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idPTTT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPttt"));

                    b.Property<string>("Tenphuongthuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tenphuongthuc");

                    b.HasKey("IdPttt")
                        .HasName("PK__PhuongTh__DE0378267CCB0FE1");

                    b.ToTable("PhuongThucThanhToan", (string)null);
                });

            modelBuilder.Entity("QUANLYBANMAYANH_NHOM24.Models.SanPham", b =>
                {
                    b.Property<int>("Idsanpham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idsanpham");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idsanpham"));

                    b.Property<string>("DiachianhSp")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("diachianhSP");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("gia");

                    b.Property<int>("Iddanhmuccon")
                        .HasColumnType("int")
                        .HasColumnName("iddanhmuccon");

                    b.Property<int?>("Idhang")
                        .HasColumnType("int")
                        .HasColumnName("idhang");

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mota");

                    b.Property<int>("Soluongcon")
                        .HasColumnType("int")
                        .HasColumnName("soluongcon");

                    b.Property<string>("Tensp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tensp");

                    b.HasKey("Idsanpham")
                        .HasName("PK__SanPham__C5FDB0E5641EF42A");

                    b.HasIndex("Iddanhmuccon");

                    b.HasIndex("Idhang");

                    b.ToTable("SanPham", (string)null);
                });

            modelBuilder.Entity("QUANLYBANMAYANH_NHOM24.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("QUANLYBANMAYANH_NHOM24.Models.DonHang", "IddonhangNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("Iddonhang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietDo__iddon__5629CD9C");

                    b.HasOne("QUANLYBANMAYANH_NHOM24.Models.SanPham", "IdsanphamNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("Idsanpham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietDo__idsan__571DF1D5");

                    b.Navigation("IddonhangNavigation");

                    b.Navigation("IdsanphamNavigation");
                });

            modelBuilder.Entity("QUANLYBANMAYANH_NHOM24.Models.DanhMucCon", b =>
                {
                    b.HasOne("QUANLYBANMAYANH_NHOM24.Models.DanhMuc", "IddanhmucNavigation")
                        .WithMany("DanhMucCons")
                        .HasForeignKey("Iddanhmuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__DanhMucCo__iddan__3C69FB99");

                    b.Navigation("IddanhmucNavigation");
                });

            modelBuilder.Entity("QUANLYBANMAYANH_NHOM24.Models.DiaChiGiaoHang", b =>
                {
                    b.HasOne("QUANLYBANMAYANH_NHOM24.Models.NguoiDung", "IdnguoidungNavigation")
                        .WithMany("DiaChiGiaoHangs")
                        .HasForeignKey("Idnguoidung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__DiaChiGia__idngu__46E78A0C");

                    b.Navigation("IdnguoidungNavigation");
                });

            modelBuilder.Entity("QUANLYBANMAYANH_NHOM24.Models.DonHang", b =>
                {
                    b.HasOne("QUANLYBANMAYANH_NHOM24.Models.PhuongThucThanhToan", "IdPtttNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("IdPttt")
                        .IsRequired()
                        .HasConstraintName("FK__DonHang__idPTTT__534D60F1");

                    b.HasOne("QUANLYBANMAYANH_NHOM24.Models.DiaChiGiaoHang", "IddiachiNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("Iddiachi")
                        .IsRequired()
                        .HasConstraintName("FK__DonHang__iddiach__52593CB8");

                    b.HasOne("QUANLYBANMAYANH_NHOM24.Models.NguoiDung", "IdnguoidungNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("Idnguoidung")
                        .IsRequired()
                        .HasConstraintName("FK__DonHang__idnguoi__5165187F");

                    b.Navigation("IdPtttNavigation");

                    b.Navigation("IddiachiNavigation");

                    b.Navigation("IdnguoidungNavigation");
                });

            modelBuilder.Entity("QUANLYBANMAYANH_NHOM24.Models.DonHangKhuyenMai", b =>
                {
                    b.HasOne("QUANLYBANMAYANH_NHOM24.Models.DonHang", "IddonhangNavigation")
                        .WithMany("DonHangKhuyenMais")
                        .HasForeignKey("Iddonhang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__DonHangKh__iddon__60A75C0F");

                    b.HasOne("QUANLYBANMAYANH_NHOM24.Models.KhuyenMai", "IdkhuyenmaiNavigation")
                        .WithMany("DonHangKhuyenMais")
                        .HasForeignKey("Idkhuyenmai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__DonHangKh__idkhu__619B8048");

                    b.Navigation("IddonhangNavigation");

                    b.Navigation("IdkhuyenmaiNavigation");
                });

            modelBuilder.Entity("QUANLYBANMAYANH_NHOM24.Models.GioHang", b =>
                {
                    b.HasOne("QUANLYBANMAYANH_NHOM24.Models.NguoiDung", "IdnguoidungNavigation")
                        .WithMany("GioHangs")
                        .HasForeignKey("Idnguoidung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__GioHang__idnguoi__59FA5E80");

                    b.HasOne("QUANLYBANMAYANH_NHOM24.Models.SanPham", "IdsanphamNavigation")
                        .WithMany("GioHangs")
                        .HasForeignKey("Idsanpham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__GioHang__idsanph__5AEE82B9");

                    b.Navigation("IdnguoidungNavigation");

                    b.Navigation("IdsanphamNavigation");
                });

            modelBuilder.Entity("QUANLYBANMAYANH_NHOM24.Models.NguoiDungPhanQuyen", b =>
                {
                    b.HasOne("QUANLYBANMAYANH_NHOM24.Models.NguoiDung", "IdnguoidungNavigation")
                        .WithMany("NguoiDungPhanQuyens")
                        .HasForeignKey("Idnguoidung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__NguoiDung__idngu__6754599E");

                    b.HasOne("QUANLYBANMAYANH_NHOM24.Models.PhanQuyen", "IdphanquyenNavigation")
                        .WithMany("NguoiDungPhanQuyens")
                        .HasForeignKey("Idphanquyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__NguoiDung__idpha__68487DD7");

                    b.Navigation("IdnguoidungNavigation");

                    b.Navigation("IdphanquyenNavigation");
                });

            modelBuilder.Entity("QUANLYBANMAYANH_NHOM24.Models.SanPham", b =>
                {
                    b.HasOne("QUANLYBANMAYANH_NHOM24.Models.DanhMucCon", "IddanhmucconNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("Iddanhmuccon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__SanPham__iddanhm__412EB0B6");

                    b.HasOne("QUANLYBANMAYANH_NHOM24.Models.Hang", "IdhangNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("Idhang")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__SanPham__idhang__4222D4EF");

                    b.Navigation("IddanhmucconNavigation");

                    b.Navigation("IdhangNavigation");
                });

            modelBuilder.Entity("QUANLYBANMAYANH_NHOM24.Models.DanhMuc", b =>
                {
                    b.Navigation("DanhMucCons");
                });

            modelBuilder.Entity("QUANLYBANMAYANH_NHOM24.Models.DanhMucCon", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("QUANLYBANMAYANH_NHOM24.Models.DiaChiGiaoHang", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("QUANLYBANMAYANH_NHOM24.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("DonHangKhuyenMais");
                });

            modelBuilder.Entity("QUANLYBANMAYANH_NHOM24.Models.Hang", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("QUANLYBANMAYANH_NHOM24.Models.KhuyenMai", b =>
                {
                    b.Navigation("DonHangKhuyenMais");
                });

            modelBuilder.Entity("QUANLYBANMAYANH_NHOM24.Models.NguoiDung", b =>
                {
                    b.Navigation("DiaChiGiaoHangs");

                    b.Navigation("DonHangs");

                    b.Navigation("GioHangs");

                    b.Navigation("NguoiDungPhanQuyens");
                });

            modelBuilder.Entity("QUANLYBANMAYANH_NHOM24.Models.PhanQuyen", b =>
                {
                    b.Navigation("NguoiDungPhanQuyens");
                });

            modelBuilder.Entity("QUANLYBANMAYANH_NHOM24.Models.PhuongThucThanhToan", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("QUANLYBANMAYANH_NHOM24.Models.SanPham", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("GioHangs");
                });
#pragma warning restore 612, 618
        }
    }
}
